(cl:defpackage imagelistener-srv
  (:use )
  (:export
   "EXAMPLEIMAGEPROCESSING"
   "<EXAMPLEIMAGEPROCESSING-REQUEST>"
   "EXAMPLEIMAGEPROCESSING-REQUEST"
   "<EXAMPLEIMAGEPROCESSING-RESPONSE>"
   "EXAMPLEIMAGEPROCESSING-RESPONSE"
   "IMAGEVIEWING"
   "<IMAGEVIEWING-REQUEST>"
   "IMAGEVIEWING-REQUEST"
   "<IMAGEVIEWING-RESPONSE>"
   "IMAGEVIEWING-RESPONSE"
  ))

