(cl:defpackage imagelistener-srv
  (:use )
  (:export
   "EXAMPLEIMAGEPROCESSING"
   "<EXAMPLEIMAGEPROCESSING-REQUEST>"
   "EXAMPLEIMAGEPROCESSING-REQUEST"
   "<EXAMPLEIMAGEPROCESSING-RESPONSE>"
   "EXAMPLEIMAGEPROCESSING-RESPONSE"
  ))

